#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Started...'

pnpm format ||
(
    echo 'Prettier failed';
    false;
)

# Check ESLint Standards
pnpm run lint ||
(
        echo 'ESLint failed'
        false; 
)

# Check tsconfig standards
pnpm run types ||
(
    echo 'Typescript failed'
    false;
)

echo 'Almost good'

pnpm build ||
(
    echo 'build error'
    false;
)

echo 'done'
